FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y cowsay fortune-mod netcat-openbsd && \
    apt-get clean

ENV PATH="/usr/games:${PATH}"

WORKDIR /usr/local/bin/app

COPY wisecow.sh /usr/local/bin/app/

RUN chmod +x /usr/local/bin/app/wisecow.sh

EXPOSE 4499

CMD ["./wisecow.sh"]
